SCIEX-digitalMarketing/sciex-eds

fstab.yaml

Test URLs:
- Before: https://main--{repo}--{owner}.aem.live/
- After: https://<branch>--{repo}--{owner}.aem.live/

Update fstab.yaml to point to Dev1

---

paths.json

Test URLs:
- Before: https://main--{repo}--{owner}.aem.live/
- After: https://<branch>--{repo}--{owner}.aem.live/

Update paths.json to /content/sciex-eds

---

blocks/footer/footer.css
blocks/footer/footer.js
blocks/sciex-footer-new/_sciex-footer-new.json
component-definition.json
component-models.json

Test URLs:
- After: https://feature-sciex-footer--sciex-eds--sciex-digitalmarketing.aem.live/

Sciex Compoment Initial

---

blocks/sciex-footer-new/sciex-footer-new.js

Test URLs:
- After: https://feature-footer-sciex--sciex-eds--sciex-digitalmarketing.aem.live/

Sciex-footer Changes

---

blocks/header/_header.json
blocks/header/header.js
component-definition.json
component-filters.json
component-models.json

Test URLs:
- After: https://feature-mega-menu--sciex-eds--sciex-digitalmarketing.aem.live/

Mega menu first level

---

component-filters.json
models/_section.json

Test URLs:
After: https://feature-mega-menu--sciex-eds--sciex-digitalmarketing.aem.live/

Header added in section json file

---

models/_component-models.json
models/_page-metadata.json

Test URLs:
* After: https://feature-page-properties--sciex-eds--sciex-digitalmarketing.aem.live/

Page properties implementation.

---

component-models.json

Test URLs:
 •Before: https://main--sciex-eds--sciex-digitalmarketing.aem.live/
* After: https://feature-page-properties--sciex-eds--sciex-digitalmarketing.aem.live/

Updated Page properties section

---

blocks/login-sso/_login-sso.json
blocks/login-sso/login-sso.js
component-definition.json
component-models.json
models/_section.json

Test URLs:
* After: https://feature-header-sso--sciex-eds--sciex-digitalmarketing.aem.live/

Login cookie Poc Block

---

blocks/login-sso/_login-sso.json
blocks/login-sso/login-sso.js
component-definition.json
component-filters.json
component-models.json
models/_section.json

Test URLs:
* After: https://feature-header-sso--sciex-eds--sciex-digitalmarketing.aem.live/

Feature header sso

---

component-models.json
models/_page-metadata.json

Test URLs:
- After: https://feature-page-propertiesA--sciex-eds--SCIEX-digitalMarketing.aem.live/

Meta Page Properties

---

blocks/footer/footer.css
blocks/footer/footer.js
icons/chevron-up.svg
styles/fonts.css

Test URLs:
* After: https://feature-footer-styling--sciex-eds--sciex-digitalmarketing.aem.live/

Footer Styling Chanhges

---

blocks/searchresult/searchresult.js
package.json
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-searchresults-factes--sciex-eds--sciex-digitalmarketing.aem.live/

searchresults factes realted code changes

---

blocks/searchresult/_searchresult.json
component-models.json

Test URLs:
After: https://no-search-results--sciex-eds--sciex-digitalmarketing.aem.page/

Search no results json changes.

---

blocks/footer/footer.css
blocks/footer/footer.js

Test URLs:
- After: https://feature-footer-style--sciex-eds--SCIEX-digitalMarketing.aem.page/

update footer styling

---

blocks/searchresult/_searchresult.json
component-definition.json
component-models.json

Test URLs:
After: https://no-search-results--sciex-eds--sciex-digitalmarketing.aem.page/

No search results

---

blocks/breadcrumb/_breadcrumb.json
blocks/breadcrumb/breadcrumb.css
blocks/breadcrumb/breadcrumb.js
component-definition.json
scripts/scripts.js

 •Before: https://main--sciex-eds--sciex-digitalmarketing.aem.live/
* After: https://feature-breadcrumb--sciex-eds--sciex-digitalmarketing.aem.live/

Breadcrumb block

---

component-filters.json
models/_section.json

* After: https://feature-breadcrumb--sciex-eds--sciex-digitalmarketing.aem.live/

Bread Setion changes

---

blocks/header/header.css
blocks/header/header.js
blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/pagination.js
scripts/searchresult/components/searchResult.js
styles/styles.css

Test URLs:
After: https://no-search-results--sciex-eds--sciex-digitalmarketing.aem.page/

Search results and menu responsive changes

---

scripts/searchresult/components/searchResult.js
scripts/searchresult/components/sorting.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-sorting--sciex-eds--SCIEX-digitalMarketing.aem.live/

Sorting code changes for searchresults

---

blocks/footer/footer.css
blocks/footer/footer.js
blocks/header/header.css
blocks/header/header.js
blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/searchResult.js

Test URLs:
After: https://feature-responsive--sciex-eds--sciex-digitalmarketing.aem.page/

Search results  and Mega menu responsive changes.

---

blocks/header/header.js
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-search-results--sciex-eds--SCIEX-digitalMarketing.aem.live/

Search Results Facets related code changes

---

blocks/footer/footer.css
blocks/header/header.css
blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/searchResult.js

Test URLs:
After: https://feature-responsive-menu--sciex-eds--sciex-digitalmarketing.aem.page/

Header and Search results CSS changes

---

scripts/scripts.js

* After: https://feature-one-trust--sciex-eds--sciex-digitalmarketing.aem.live/

Changes in script

---

scripts/scripts.js

* After: https://feature-one-trust--sciex-eds--sciex-digitalmarketing.aem.live/

One trust Decode call back url changes.

---

scripts/scripts.js

* After: https://feature-gtTag--sciex-eds--sciex-digitalmarketing.aem.live/

One trust changes

---

blocks/searchresult/searchresult.css
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-coveo-fixes--sciex-eds--sciex-digitalmarketing.aem.live/

Fix child facet and  extra line appearing on search facet

---

component-models.json
models/_page-metadata.json

Test URLs:
- After: https://feature-metadata-robots--sciex-eds--SCIEX-digitalMarketing.aem.page/

fixed metarobots name

---

blocks/footer/footer.js
scripts/scripts.js

* After: https://feature-gtTag--sciex-eds--sciex-digitalmarketing.aem.live/

Footer hrr tag issue.

---

blocks/footer/footer.js

* After: https://feature-footer-Hr--sciex-eds--sciex-digitalmarketing.aem.live/

Footer extra HR tag Issue Fix

---

blocks/searchresult/searchresult.css
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/facetBreadcrumb.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-ordering-facets--sciex-eds--sciex-digitalmarketing.aem.aem.live/

Implement ordering for facets.

---

blocks/footer/footer.css
blocks/footer/footer.js
blocks/header/header.js
blocks/searchresult/searchresult.css
scripts/searchresult/components/categoryFacets.js

Test URLs:
After: https://feature-design-issues--sciex-eds--sciex-digitalmarketing.aem.page/

Header , Footer and Search results css changes.

---

scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/renderSearchResult.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-facets-changes--sciex-eds--sciex-digitalmarketing.aem.live/

Fix content type and source label issue.

---

blocks/header/header.js
blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/facetBreadcrumb.js

Test URLs:
After: https://feature-searchresults-mobile--sciex-eds--sciex-digitalmarketing.aem.live/

Search results mobile view changes.

---

blocks/footer/footer.js
blocks/header/header.js
blocks/login-sso/login-sso.js
blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/scripts.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/facetBreadcrumb.js

Test URLs:
After: https://disable-gtmscript-author--sciex-eds--sciex-digitalmarketing.aem.live/

Disable gtmscript author and rebase changes

---

blocks/footer/footer.js

* After: https://feature-cookie-seeting--sciex-eds--sciex-digitalmarketing.aem.live/

Cookie setting Changes for Footer

---

blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/facetBreadcrumb.js
scripts/searchresult/components/renderSearchBox.js
scripts/searchresult/components/renderSearchResult.js

Test URLs:
- After: https://feature-pagejump-issues--sciex-eds--sciex-digitalmarketing.aem.live/

Fix Page jump issue and no result found styling

---

blocks/searchresult/searchresult.css

* After: https://feature-font-issues--sciex-eds--sciex-digitalmarketing.aem.live/

Font issues in no-search result page

---

blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/facetBreadcrumb.js
scripts/searchresult/components/renderSearchBox.js

Test URLs:
- After: https://feature-pagejump-issue--sciex-eds--sciex-digitalmarketing.aem.live/

Fix Page jump issue, add search and clear icon.

---

blocks/footer/footer.js
blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/facetBreadcrumb.js
scripts/searchresult/components/renderSearchResult.js

Test URLs:
- After: https://feature-application-facet--sciex-eds--sciex-digitalmarketing.aem.live/

Fix application facet issue and clear all styling.

---

blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/facetBreadcrumb.js
scripts/searchresult/components/querySummary.js

Test URLs:
- After: https://feature-mobilefilter-issue--sciex-eds--sciex-digitalmarketing.aem.live/

Fix mobile filter styling and functional issue.

---

scripts/searchresult/components/categoryFacets.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-context-variable--sciex-eds--digitalmarketing.aem.live/

Implement context variable along with the host path.

---

blocks/header/header.js
blocks/searchresult/searchresult.css
scripts/searchresult/components/facetBreadcrumb.js

Test URLs:
After: https://feature-menu-desc--sciex-eds--digitalmarketing.aem.live/

Menu anchor with description and mobile filter show less changes.

---

fstab.yaml

Test URLs:
- After: https://feature-stage-setup--sciex-eds--SCIEX-digitalMarketing.aem.live/

Modified fstab file with stage URL

---

blocks/searchresult/searchresult.js

Test URLs:
- After: https://feature-pathname-issue--sciex-eds--sciex-digitalmarketing..aem.live/

Fix path name in search result.

---

blocks/breadcrumb/breadcrumb.css
blocks/footer/footer.css
blocks/header/header.css
blocks/searchresult/searchresult.css
scripts/searchresult/components/facetBreadcrumb.js
styles/site.css

Test URLs:
After: https://feature-menu-desc--sciex-eds--digitalmarketing.aem.live/

Menu and footer mobile css changes

---

blocks/searchresult/_searchresult.json
component-models.json

Test URLs:
- After: https://feature-coveo-config-fields--sciex-eds--SCIEX-digitalMarketing.aem.live/

Added coveo fields in searchresults block

---

blocks/header/header.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/controller/controllers.js
scripts/searchresult/engine.js

Test URLs:
- After: https://feature-searchengine-fixes--sciex-eds--sciex-digitalmarketing.aem.live/

Implement dynamic value fetching for orgId and Access token.

---

blocks/header/header.css
blocks/header/header.js

Test URLs:
After: https://feature-menu-desc--sciex-eds--digitalmarketing.aem.live/

Feature menu desc

---

blocks/header/header.css
blocks/header/header.js

Test URLs:
After: https://feature-menu-desc--sciex-eds--digitalmarketing.aem.live/

Mega menu image clickable changes

---

blocks/searchresult/searchresult.css
scripts/searchresult/components/renderSearchResult.js

Test URLs:
- After: https://feature-description-limit--sciex-eds--sciex-digitalmarketing.aem.live/

Fix the limit of 3 line to the description.

---

fstab.yaml

Test URLs:
- After: https://feature-update-fstab--sciex-eds--sciex-digitalmarketing.aem.live/

Updated to Prod AEM

---

scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/renderSearchBox.js

Test URLs:
- After: https://feature-ui-fixes--sciex-eds--sciex-digitalmarketing.aem.live/

Fix Ui issue for suggestion popup and input box

---

.github/workflows/main.yaml
fstab.yaml

Test URLs:
- Before: https://main--sciex-eds--Venkatalakshmi-nelluri.aem.live/
- After: https://feature-dev-branch--sciex-eds--Venkatalakshmi-nelluri.aem.live/

Updated fstab with environment varaibles

---

blocks/header/header.js
component-models.json
models/_page-metadata.json
scripts/searchresult/components/renderSearchBox.js

Test URLs:
- After: https://feature-search-survey--sciex-eds--SCIEX-digitalMarketing.aem.live/

Search survey changes

---

scripts/searchresult/components/renderSearchBox.js

Test URLs:
After: https://feature-search-survey--sciex-eds--sciex-digitalmarketing.aem.live/

import added

---

blocks/breadcrumb/breadcrumb.js

Test URLs:
Before: https://main--sciex-eds--SCIEX-digitalMarketing.aem.live/
After: https://feature-breadcrumb-fix--sciex-eds--SCIEX-digitalMarketing.aem.live/

Breadcrumb order fix

---

blocks/searchresult/searchresult.css
blocks/searchresult/searchresult.js
scripts/searchresult/components/categoryFacets.js
scripts/searchresult/components/renderSearchBox.js
scripts/searchresult/components/renderSearchResult.js
scripts/searchresult/components/sorting.js
scripts/searchresult/controller/controllers.js
scripts/searchresult/engine.js

Test URLs:
- After: https://feature-search-result--sciex-eds--sciex-digitalmarketing.aem.live/

Functional and UI fixes for search result.

---

blocks/header/header.css
blocks/header/header.js
scripts/header-search/headerSearchController.js
scripts/header-search/headerSearchEngine.js

Test URLs:
- After: https://feature-header-search--sciex-eds--sciex-digitalmarketing.aem.live/

Implement standalone search for header.

---

blocks/coursecatalog/_coursecatalog.json
blocks/coursecatalog/coursecatalog.css
blocks/coursecatalog/coursecatalog.js
component-definition.json
component-filters.json
component-models.json
models/_section.json
scripts/course-catalog/components/courseCatalogFacet.js
scripts/course-catalog/components/courseCatalogFacetBreadcurm.js
scripts/course-catalog/components/courseCatalogPagination.js
scripts/course-catalog/components/courseCatalogQuerySummary.js
scripts/course-catalog/components/courseCatalogSorting.js
scripts/course-catalog/components/renderCourseCatalogSearchBox.js
scripts/course-catalog/components/renderCourseCatalogSearchResult.js
scripts/course-catalog/course-catalog-controller/controllers.js
scripts/course-catalog/courseCatalogEngine.js

Test URLs:
- After: https://feature-course-catalog--sciex-eds--sciex-digitalmarketing.aem.live/

Implement course catalog.

---

blocks/footer/footer.css
blocks/footer/footer.js
component-models.json
models/_page-metadata.json

Test URLs:
After: https://feature-pagetracking-id--sciex-eds--sciex-digitalmarketing.aem.live/

Changes for page tracking id

---

scripts/header-search/headerSearchEngine.js

Test URLs:
- After: https://feature-access-token--sciex-eds--sciex-digitalmarketing.aem.live/

Updated the access token for prod

---

blocks/button-text/button-text.js

Fix for button-text block

---

blocks/footer/footer.css

Missed changes in footer

---

blocks/header/header.css
blocks/tabs-nav/tabs-nav.js

Test URLs:
- After: https://feature-tabnav-issue--sciex-eds--sciex-digitalmarketing.aem.live/

Fix Tech note tab and mobile header issue

---

blocks/sciex-related-resource/_sciex-related-resource.json

Removing default text

---

component-models.json

Removing default text to related resources

---

blocks/tabs-container/tabs-container.css

Test URLs:
- After: https://feature-tech-note-pages--sciex-eds--sciex-digitalmarketing.aem.live/

Tab container css changes

---

blocks/header/header.css
blocks/header/header.js
blocks/tabs-nav/tabs-nav.css
blocks/tabs-nav/tabs-nav.js

Test URLs:
- Before: https://main--sciex-eds--sciex-digitalmarketing.aem.live//
- After: https://feature-technote-bugs--sciex-eds--sciex-digitalmarketing.aem.live/

Fix Tech note  and mobile header issue

---

blocks/tabs-nav/tabs-nav.js

Test URLs:
Before: https://main--sciex-eds--sciex-digitalmarketing.aem.live//

Changes in tabs nav hide logic

---

blocks/tabs-nav/tabs-nav.js

Test URLs:
- After: https://feature-tech-note-pages--sciex-eds--sciex-digitalmarketing.aem.live/

Tab Nav text change - Jump To

---

blocks/customer-document/_customer-document.json
blocks/customer-document/customer-document.css
blocks/customer-document/customer-document.js
component-definition.json
component-filters.json
component-models.json
models/_section.json
scripts/common-components/commonFacetBreadcurm.js
scripts/common-components/commonFacets.js
scripts/common-components/commonPagination.js
scripts/common-components/commonQuerySummary.js
scripts/common-components/commonRenderSearchBox.js
scripts/common-components/commonSearchResultList.js
scripts/common-components/commonSorting.js
scripts/common-components/renderUI.js
scripts/common-components/sortiingUtils.js
scripts/customer-documents/customer-document-controller/customerDocControllers.js
scripts/customer-documents/customerDocEngine.js
styles/styles.css

Test URLs:
- After: https://feature-customer-document--sciex-eds--sciex-digitalmarketing.aem.live/

Implement customer document search page.

---

blocks/header/header.css

Test URLs:
- After: https://feature-performance-issues--sciex-eds--sciex-digitalmarketing.aem.live/

Perfomance issues fix

---

component-models.json
models/_page-metadata.json
scripts/scripts.js

GTM FallBack script

---

scripts/course-catalog/components/renderCourseCatalogSearchResult.js

Test URLs:
- After: https://bugfix-course-catalog-issue--sciex-eds--sciex-digitalmarketing.aem.live/

Course Catalog show text issue

---

blocks/header/header.js

Test URLs:
- After: https://bug-global-search--sciex-eds--sciex-digitalmarketing.aem.live/

Fix global search filter issue.

---

scripts/course-catalog/components/renderCourseCatalogSearchResult.js
scripts/course-catalog/course-catalog-controller/controllers.js

Test URLs:
- After: https://feature-course-rating--sciex-eds--sciex-digitalmarketing..aem.live/

Fix course catalog rating.

---

scripts/course-catalog/components/courseCatalogFacet.js

Test URLs:
- After: https://feature-facet-order--sciex-eds--sciex-digitalmarketing..aem.live/

Change course catalog facet order.

---

blocks/sciex-title/sciex-title.css
blocks/sciex-title/sciex-title.js

Test URLs:
- After: https://feature-styling-fix--sciex-eds--sciex-digitalmarketing.aem.live/

Fix styling for performance

---

blocks/tabs-nav/tabs-nav.js

Test URLs:
- After: https://feature-tabnavs-issue--sciex-eds--sciex-digitalmarketing.aem.live/

Fix tab nav navigation issue

---

blocks/sciex-title/sciex-title.css

Test URLs:
- After: https://feature-technotes-issues--sciex-eds--sciex-digitalmarketing.aem.live/

Added min height for sciex-title

---

blocks/header/header.js

Test URLs:
Before: https://main--sciex-eds--sciex-eds-nonprod.aem.live/
After: https://feature-logout-button-issue--sciex-eds--sciex-eds-nonprod.aem.live/

Logout button showing issue fix

---

icons/white-arrow.svg

Test URLs:
- After: https://feature-arrow-icon--sciex-eds--SCIEX-digitalMarketing.aem.live/

Add arrow icon

---

blocks/featured-products/_featured-products.json
blocks/featured-products/featured-products.js
blocks/footer/footer.js
component-models.json

Adding alt and title attribute for blocks

---

scripts/searchresult/components/categoryFacets.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-ecommerce-fixes--sciex-eds--ciex-digitalmarketing.aem.live/

Fix binary data to eCommerce.

---

scripts/searchresult/components/facetBreadcrumb.js

Please always provide the [GitHub issue(s)](https://github.com/SCIEX-digitalMarketing/sciex-eds/issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #
Test URLs:
After: https://feature-ecommerce-fixes--sciex-eds--ciex-digitalmarketing.aem.live/

Fix binary data to ecommerce

---

blocks/header/header.css
blocks/header/header.js
scripts/common-components/commonRenderSearchBox.js
scripts/course-catalog/components/renderCourseCatalogSearchBox.js
scripts/course-catalog/course-catalog-controller/controllers.js
scripts/customer-documents/customer-document-controller/customerDocControllers.js
scripts/header-search/headerSearchController.js
scripts/regulatory-document/regulatory-document-controller/regulatoryDocControllers.js
scripts/searchresult/components/renderSearchBox.js
scripts/searchresult/controller/controllers.js

Test URLs:
- After: https://feature-query-suggession--sciex-eds--sciex-digitalmarketing.aem.live/

Implement Query suggession for all the search

---

blocks/cards/_cards.json
component-models.json

Test URLs:
After: https://feature-cards-block--sciex-eds--sciex-digitalmarketing.aem.live/

Changes in cards block

---

component-filters.json
models/_section.json

Test URLs:
After: https://feature-sync-code-nonprod-to-prod--sciex-eds--sciex-digitalmarketing.aem.live/

Events blocks added

---

blocks/tabs-nav/tabs-nav.css
blocks/tabs-nav/tabs-nav.js

Test URLs:
After: https://feature-sync-code-nonprod-to-prod--sciex-eds--sciex-digitalmarketing.aem.live/

Tab nav changes added

---

blocks/tabs-container/tabs-container.css
blocks/tabs-nav/tabs-nav.css

Test URLs:
After: https://feature-sync-code-nonprod-to-prod--sciex-eds--sciex-digitalmarketing.aem.live/

Tab nav issue fix.

---

blocks/events-container/events-container.css
blocks/tabs-nav/tabs-nav.css

Test URLs:
After: https://feature-css-fix--sciex-eds--sciex-digitalmarketing.aem.live/

CSS issues in blocks

---

scripts/header-search/headerSearchEngine.js

Test URLs:
After: https://feature-endpoint-issue--sciex-eds--sciex-digitalmarketing.aem.live/

Wrong end point usage
